# Generated by Django 2.2.13 on 2020-07-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0003_auto_20200720_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDrivePublicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=5000)),
                ('link', models.CharField(max_length=5000)),
                ('file_name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleMailAccountCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NaughtyOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NonOfficerGithubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=5000)),
                ('username', models.CharField(max_length=5000)),
                ('legal_name', models.CharField(default='NA', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='NonOfficerGoogleDriveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('file_id', models.CharField(max_length=5000)),
                ('file_name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='NonOfficerMaillistMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maillist_name', models.CharField(max_length=5000)),
                ('sfuid', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerGithubTeamMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='President', max_length=300)),
                ('team_name', models.CharField(default='officers', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessNewOfficer',
            fields=[
                ('passphrase', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('term', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', help_text='You need to click on the dropbox above in order for the slug field to get populated', max_length=6)),
                ('year', models.IntegerField(choices=[(2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970)], default='2018', help_text='You need to click on the dropbox above in order for the slug field to get populated')),
                ('position', models.CharField(default='President', max_length=300)),
                ('term_position_number', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=300)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerGithubTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=5000)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Officer')),
            ],
        ),
    ]
