# Generated by Django 2.2.13 on 2020-09-15 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processnewofficer',
            name='new_start_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processnewofficer',
            name='sfu_officer_mailing_list_email',
            field=models.CharField(default='NA', max_length=140),
        ),
        migrations.AddField(
            model_name='processnewofficer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
