# Generated by Django 2.2.13 on 2020-12-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0002_auto_20200915_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officergithubteammapping',
            old_name='position',
            new_name='position_name',
        ),
        migrations.RenameField(
            model_name='processnewofficer',
            old_name='term_position_number',
            new_name='position_index',
        ),
        migrations.RenameField(
            model_name='processnewofficer',
            old_name='position',
            new_name='position_name',
        ),
    ]
