# Generated by Django 2.2.13 on 2021-01-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20210110_1721'),
        ('resource_management', '0003_auto_20201216_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerPositionGithubTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='officers', max_length=300)),
                ('marked_for_deletion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerPositionGithubTeamMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resource_management.OfficerPositionGithubTeam')),
                ('officer_position_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.OfficerEmailListAndPositionMapping')),
            ],
        ),
        migrations.DeleteModel(
            name='NonOfficerMaillistMember',
        ),
        migrations.RemoveField(
            model_name='officergithubteam',
            name='officer',
        ),
        migrations.DeleteModel(
            name='OfficerGithubTeamMapping',
        ),
        migrations.AlterField(
            model_name='processnewofficer',
            name='year',
            field=models.IntegerField(choices=[(2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970)], default='2018', help_text='You need to click on the dropbox above in order for the slug field to get populated'),
        ),
        migrations.DeleteModel(
            name='OfficerGithubTeam',
        ),
    ]
