# Generated by Django 2.2.13 on 2021-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0004_auto_20210110_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerpositiongithubteam',
            name='relevant_previous_terms',
            field=models.IntegerField(default=0),
        ),
    ]
