# Generated by Django 2.2.13 on 2021-01-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0004_auto_20210119_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naughtyofficer',
            name='name',
        ),
        migrations.AddField(
            model_name='naughtyofficer',
            name='sfuid',
            field=models.CharField(default='NA', max_length=300),
        ),
    ]
