# Generated by Django 2.2.27 on 2022-07-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0008_auto_20220307_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleMailAccountCredentials',
        ),
    ]
