# Generated by Django 2.2.27 on 2022-08-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0009_delete_googlemailaccountcredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naughtyofficer',
            old_name='sfuid',
            new_name='sfu_computing_id',
        ),
    ]
