# Generated by Django 2.2.27 on 2022-08-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0010_auto_20220812_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NaughtyOfficer',
        ),
    ]
