# Generated by Django 2.2.27 on 2022-08-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0011_auto_20220817_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveFileAwaitingOwnershipChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=5000)),
                ('file_name', models.CharField(max_length=5000)),
                ('web_link', models.CharField(max_length=5000)),
                ('file_owner', models.CharField(max_length=5000)),
                ('number_of_nags', models.IntegerField(default=0)),
                ('latest_date_check', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveRootFolderBadAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=5000)),
                ('user', models.CharField(max_length=5000)),
                ('number_of_nags', models.IntegerField(default=0)),
                ('latest_date_check', models.DateTimeField()),
            ],
        ),
    ]
