# Generated by Django 2.2.27 on 2022-09-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0012_googledrivefileawaitingownershipchange_googledriverootfolderbadaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveNonMediaFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=500)),
                ('file_extension', models.CharField(blank=True, max_length=500)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MediaToBeMoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=500)),
                ('parent_folder_link', models.CharField(max_length=1000)),
                ('parent_folder_id', models.CharField(max_length=500)),
            ],
        ),
    ]
