# Generated by Django 2.2.27 on 2022-09-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0013_googledrivenonmediafiletype_mediatobemoved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaToBeMoved',
        ),
    ]
