# Generated by Django 2.2.27 on 2022-09-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0014_delete_mediatobemoved'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaToBeMoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=5000)),
                ('parent_folder_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
