# Generated by Django 2.2.28 on 2022-09-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0017_delete_googledrivefileawaitingownershipchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveFileAwaitingOwnershipChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=5000)),
                ('file_name', models.CharField(max_length=5000)),
                ('file_path', models.CharField(max_length=5000)),
                ('parent_folder_link', models.CharField(max_length=5000)),
                ('file_owner', models.CharField(max_length=5000)),
                ('number_of_nags', models.IntegerField(default=0)),
                ('latest_date_check', models.DateTimeField()),
            ],
        ),
    ]
