# Generated by Django 2.2.27 on 2023-06-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0019_auto_20230411_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatobemoved',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
