# Generated by Django 2.2.27 on 2023-06-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0019_auto_20230411_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatobemoved',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediatobemoved',
            name='file_id',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
