# Generated by Django 2.2.27 on 2023-06-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0020_mediatobemoved_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatobemoved',
            name='file_id',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
