# Generated by Django 2.2.27 on 2023-06-24 09:39

import csss.PSTDateTimeField
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0021_mediatobemoved_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', csss.PSTDateTimeField.PSTDateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(max_length=500)),
                ('event_date', csss.PSTDateTimeField.PSTDateTimeField(default=django.utils.timezone.now)),
                ('relevant_note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(max_length=1000, upload_to='')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.Upload')),
            ],
        ),
    ]
