# Generated by Django 2.2.28 on 2023-07-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0022_mediaupload_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatobemoved',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
