# Generated by Django 2.2.28 on 2023-07-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0023_mediatobemoved_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='event_type_specifier',
            field=models.CharField(blank=True, default=True, max_length=500, null=True),
        ),
    ]
