# Generated by Django 2.2.9 on 2020-02-01 03:10

import announcements.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='NA', max_length=255, verbose_name='Subject')),
                ('from_header', models.CharField(default='NA', max_length=255, verbose_name='Author')),
                ('body', models.TextField(verbose_name='Body')),
                ('processed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=announcements.utils.get_attachment_save_path, verbose_name='Document')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.Post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Message attachment',
                'verbose_name_plural': 'Message attachments',
            },
        ),
    ]
