# Generated by Django 2.2.13 on 2020-10-06 17:51

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0004_auto_20200915_1744'),
        ('django_mailbox', '0008_auto_20190219_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=32, unique=True)),
                ('author', models.CharField(default=None, max_length=32)),
                ('slug', models.SlugField(default=None, max_length=32, unique=True)),
                ('content', django_markdown.models.MarkdownField(default=None)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('author', models.CharField(blank=True, default=None, max_length=200)),
                ('display', models.BooleanField(blank=True, default=None)),
                ('email', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibility_indicator', to='django_mailbox.Message')),
                ('manual_announcement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibility_indicator', to='announcements.ManualAnnouncement')),
                ('term', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relevant_announcements', to='about.Term')),
            ],
        ),
    ]
