# Generated by Django 2.2.28 on 2023-03-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualannouncement',
            old_name='content',
            new_name='old_content',
        ),
    ]
