# Generated by Django 2.2.28 on 2023-03-29 01:53

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20230328_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualannouncement',
            name='content',
            field=models.CharField(default=None, max_length=3000, null=True),
        ),
    ]
