# Generated by Django 2.2.28 on 2023-03-29 01:54

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20230328_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualannouncement',
            name='old_content',
            field=django_markdown.models.MarkdownField(default=None, null=True),
        ),
    ]
