# Generated by Django 2.2.28 on 2023-03-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20230328_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualannouncement',
            name='old_content',
        ),
    ]
