# Generated by Django 2.2.27 on 2023-04-12 01:42

import csss.PSTDateTimeField
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_remove_manualannouncement_old_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=csss.PSTDateTimeField.PSTDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='manualannouncement',
            name='date',
            field=csss.PSTDateTimeField.PSTDateTimeField(default=django.utils.timezone.now),
        ),
    ]
