# Generated by Django 2.2.28 on 2024-02-02 01:11

import csss.views.pstdatetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20230411_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=None, max_length=1000)),
                ('author_id', models.CharField(default=None, max_length=200)),
                ('content', models.CharField(default=None, max_length=3000, null=True)),
                ('date', csss.views.pstdatetime.NewPSTDateTimeField(default=django.utils.timezone.now)),
                ('channel_id', models.CharField(default=None, max_length=200, null=True)),
                ('message_id', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='pst_date',
            field=csss.views.pstdatetime.NewPSTDateTimeField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='discordannouncement',
            constraint=models.UniqueConstraint(fields=('channel_id', 'message_id'), name='unique_announcement'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='discord_announcement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibility_indicator', to='announcements.DiscordAnnouncement'),
        ),
    ]
