# Generated by Django 2.2.10 on 2020-05-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_file', models.FileField(default='exec_positions/default', upload_to='exec_positions/')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', help_text='You need to click on the dropbox above in order for the slug field to get populated', max_length=6)),
                ('term_number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('year', models.IntegerField(choices=[(2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970)], default='2018', help_text='You need to click on the dropbox above in order for the slug field to get populated')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='President', max_length=300)),
                ('term_position_number', models.IntegerField(default=0)),
                ('name', models.CharField(default='NA', max_length=140)),
                ('sfuid', models.CharField(default='NA', max_length=140)),
                ('phone_number', models.BigIntegerField(default=0)),
                ('github_username', models.CharField(default='NA', max_length=140)),
                ('gmail', models.CharField(default='NA', max_length=140)),
                ('course1', models.CharField(default='NA', max_length=100, verbose_name='First Favorite Course')),
                ('course2', models.CharField(default='NA', max_length=100, verbose_name='Second Favorite Course')),
                ('language1', models.CharField(default='NA', max_length=100, verbose_name='First Favorite Language')),
                ('language2', models.CharField(default='NA', max_length=100, verbose_name='Second Favorite Language')),
                ('bio', models.CharField(default='NA', max_length=2000)),
                ('image', models.CharField(default='NA', max_length=400, verbose_name='Link to Profile Picture')),
                ('elected_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Term')),
            ],
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='NA', max_length=140)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='about.Officer')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='NA', max_length=140)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Officer')),
            ],
        ),
    ]
