# Generated by Django 2.2.13 on 2020-07-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='json_file',
            field=models.FileField(default='officer_positions/default', upload_to='officer_positions/'),
        ),
    ]
