# Generated by Django 2.2.13 on 2020-07-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200706_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillist',
            name='officer',
        ),
        migrations.DeleteModel(
            name='SourceFile',
        ),
        migrations.DeleteModel(
            name='EmailList',
        ),
    ]
