# Generated by Django 2.2.13 on 2020-12-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200915_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='term_position_number',
            new_name='position_index',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='position',
            new_name='position_name',
        ),
        migrations.RenameField(
            model_name='officeremaillistandpositionmapping',
            old_name='term_position_number',
            new_name='position_index',
        ),
        migrations.RenameField(
            model_name='officeremaillistandpositionmapping',
            old_name='officer_position',
            new_name='position_name',
        ),
    ]
