# Generated by Django 2.2.13 on 2020-12-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20201201_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officeremaillistandpositionmapping',
            old_name='officer_position',
            new_name='position_name',
        ),
    ]
