# Generated by Django 2.2.13 on 2021-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_officeremaillistandpositionmapping_elected_via_election_officer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='officer',
            constraint=models.UniqueConstraint(fields=('position_name', 'name', 'elected_term__term_number', 'start_date'), name='unique_officer_for_term'),
        ),
    ]
