# Generated by Django 2.2.27 on 2022-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20220323_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeremaillistandpositionmapping',
            name='github',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='officeremaillistandpositionmapping',
            name='google_drive',
            field=models.BooleanField(default=True),
        ),
    ]
