# Generated by Django 2.2.27 on 2022-08-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20220724_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='sfuid',
            new_name='sfu_computing_id',
        ),
        migrations.AddField(
            model_name='officer',
            name='discord_id',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='officer',
            name='discord_nickname',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='officer',
            name='discord_username',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
