# Generated by Django 2.2.27 on 2023-05-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_auto_20230411_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeremaillistandpositionmapping',
            name='shared_position',
            field=models.BooleanField(default=False),
        ),
    ]
