# Generated by Django 2.2.28 on 2023-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_officeremaillistandpositionmapping_shared_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='bitwarden_takeover_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeremaillistandpositionmapping',
            name='bitwarden_access',
            field=models.BooleanField(default=True),
        ),
    ]
