# Generated by Django 2.2.28 on 2023-07-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_auto_20230706_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='bitwarden_takeover_needed',
            field=models.BooleanField(default=True),
        ),
    ]
