# Generated by Django 2.2.28 on 2023-07-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_auto_20230706_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeremaillistandpositionmapping',
            name='number_of_terms',
            field=models.IntegerField(blank=True, choices=[(None, 'None'), (1, '1'), (2, '2'), (3, '3')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='officeremaillistandpositionmapping',
            name='starting_month',
            field=models.IntegerField(blank=True, choices=[(None, 'None'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=3, null=True),
        ),
    ]
