# Generated by Django 2.2.28 on 2023-07-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_auto_20230706_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='bitwarden_is_set',
            field=models.BooleanField(default=False),
        ),
    ]
