FROM python:3.7.6-alpine

ARG CONTAINER_HOME_DIR

ENV CONTAINER_HOME_DIR=$CONTAINER_HOME_DIR

ARG UNIT_TEST_RESULTS

ENV UNIT_TEST_RESULTS=$UNIT_TEST_RESULTS

ARG TEST_RESULT_FILE_NAME

ENV TEST_RESULT_FILE_NAME=$TEST_RESULT_FILE_NAME

WORKDIR $CONTAINER_HOME_DIR

RUN adduser -D websiteTester

RUN chown websiteTester $CONTAINER_HOME_DIR

USER websiteTester

ENV PATH=$PATH:/home/websiteTester/.local/bin

COPY csss-site/test/test-requirements.txt ./

COPY csss-site/src ./

COPY csss-site/test/pytest.ini ./

COPY csss-site/test/setup.cfg ./

RUN /usr/local/bin/python3 -m pip --disable-pip-version-check  install --upgrade pip

RUN pip install --no-cache --upgrade pip setuptools

RUN pip install --no-cache-dir -r test-requirements.txt

RUN mkdir -p $UNIT_TEST_RESULTS

CMD ["sh" , "-c", "py.test --junitxml=${UNIT_TEST_RESULTS}/${TEST_RESULT_FILE_NAME} --show-capture=no -W error ignore::pytest.PytestDeprecationWarning" ]
