pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage('Validate Formatting') {
            steps {
                sh label: '', script: """bash -c \'
                    ./csss-site/test/line_endings.sh;
                    export ENVIRONMENT=TEST;
                    export COMPOSE_PROJECT_NAME=TEST_WEBSITE_"${BRANCH_NAME}";

                    export CONTAINER_HOME_DIR=/usr/src/app;
                    export CONTAINER_TEST_DIR="\${CONTAINER_HOME_DIR}"/tests;
                    export CONTAINER_SRC_DIR="\${CONTAINER_HOME_DIR}"/src;

                    export LOCALHOST_SRC_DIR=${WORKSPACE}/website/src/;
                    export LOCALHOST_TEST_DIR=test_results;
                    export TEST_RESULT_FILE_NAME=all-unit-tests.xml;
                    export LOCALHOST_TEST_DIR=${WORKSPACE}/"\${LOCALHOST_TEST_DIR}";

                    export DOCKER_TEST_IMAGE="\${COMPOSE_PROJECT_NAME}"_website_pytest;
                    export DOCKER_TEST_CONTAINER="\${COMPOSE_PROJECT_NAME}"_pytest;
                    ./CI/validate_and_deploy/1_validate/run_jenkins_dockerized_formatting_test.sh;
                \'"""
            }
        }
        stage('Deploy to Test Server') {
            when { changeRequest target: 'master' }
            steps {
                withCredentials(
                    [
                        string(credentialsId: 'WEBSITE_DEV_SECRET_KEY', variable: 'WEBSITE_DEV_SECRET_KEY'),
                        string(credentialsId: 'WEBSITE_DEV_DB_PASSWORD', variable: 'WEBSITE_DEV_DB_PASSWORD'),
                        string(credentialsId: 'WEBSITE_DEV_STRIPE_SECRET_KEY', variable: 'WEBSITE_DEV_STRIPE_SECRET_KEY'),
                        string(credentialsId: 'GITHUB_ACCESS_TOKEN', variable: 'GITHUB_ACCESS_TOKEN'),
                        string(credentialsId: 'GITLAB_PRIVATE_TOKEN', variable: 'GITLAB_PRIVATE_TOKEN'),
                        string(credentialsId: 'WEBSITE_DEV_STRIPE_PUBLISHABLE_KEY', variable: 'WEBSITE_DEV_STRIPE_PUBLISHABLE_KEY'),
                        string(credentialsId: 'SFU_CSSS_GMAIL_USERNAME', variable: 'SFU_CSSS_GMAIL_USERNAME'),
                        string(credentialsId: 'SFU_CSSS_GMAIL_PASSWORD', variable: 'SFU_CSSS_GMAIL_PASSWORD'),
                        string(credentialsId: 'CSSS_DISCORD_BOT_TOKEN', variable: 'CSSS_DISCORD_BOT_TOKEN'),
                        string(credentialsId: 'SFU_ENDPOINT_TOKEN', variable: 'SFU_ENDPOINT_TOKEN')
                    ]
                ) {
                      timeout(5) {
                          sh label: '', script: """bash -c \'
                            export BRANCH_NAME=${BRANCH_NAME};
                            export CHANGE_ID=${CHANGE_ID};
                            export BASE_DIR=/home/csss/\${BRANCH_NAME};
                            export WEBSITE_SECRET_KEY="'"${WEBSITE_DEV_SECRET_KEY}"'";
                            export DEBUG=true;
                            export ENVIRONMENT=STAGING;
                            export HOST_ADDRESS=dev.sfucsss.org;

                            export GDRIVE_ROOT_FOLDER_ID="'"0B5w0O-VrxOd3UDg4Y3cyd3NFWEE"'";
                            export GDRIVE_TOKEN_LOCATION="'"/home/csss/credentials/token.pickle"'";
                            export GITHUB_ACCESS_TOKEN="'"${GITHUB_ACCESS_TOKEN}"'";
                            export GITLAB_PRIVATE_TOKEN="'"${GITLAB_PRIVATE_TOKEN}"'";
                            export SFU_CSSS_GMAIL_USERNAME="'"${SFU_CSSS_GMAIL_USERNAME}"'";
                            export SFU_CSSS_GMAIL_PASSWORD="'"${SFU_CSSS_GMAIL_PASSWORD}"'";
                            export DISCORD_BOT_TOKEN="'"${CSSS_DISCORD_BOT_TOKEN}"'";
                            export GUILD_ID="'"228761314644852736"'";
                            export SFU_ENDPOINT_TOKEN="'"${SFU_ENDPOINT_TOKEN}"'";

                            export DB_PASSWORD="'"${WEBSITE_DEV_DB_PASSWORD}"'";

                            export STRIPE_PUBLISHABLE_KEY="'"${WEBSITE_DEV_STRIPE_PUBLISHABLE_KEY}"'";
                            export STRIPE_SECRET_KEY="'"${WEBSITE_DEV_STRIPE_SECRET_KEY}"'";
                            ./CI/validate_and_deploy/2_deploy/1_update_files_on_staging_server.sh;
                            ssh csss@"\${HOST_ADDRESS}" "/home/csss/\${BRANCH_NAME}/deploy_changes.sh";
                          \'"""
                      }
                }
            }
        }
        stage('Deploy to Prod Server') {
            when {
                branch 'master'
            }
            steps {
                withCredentials(
                    [
                        string(credentialsId: 'WEBSITE_PROD_SECRET_KEY', variable: 'WEBSITE_PROD_SECRET_KEY'),
                        string(credentialsId: 'WEBSITE_PROD_DB_PASSWORD', variable: 'WEBSITE_PROD_DB_PASSWORD'),
                        string(credentialsId: 'WEBSITE_PROD_STRIPE_SECRET_KEY', variable: 'WEBSITE_PROD_STRIPE_SECRET_KEY'),
                        string(credentialsId: 'GITHUB_ACCESS_TOKEN', variable: 'GITHUB_ACCESS_TOKEN'),
                        string(credentialsId: 'GITLAB_PRIVATE_TOKEN', variable: 'GITLAB_PRIVATE_TOKEN'),
                        string(credentialsId: 'WEBSITE_PROD_STRIPE_PUBLISHABLE_KEY', variable: 'WEBSITE_PROD_STRIPE_PUBLISHABLE_KEY'),
                        string(credentialsId: 'SFU_CSSS_GMAIL_USERNAME', variable: 'SFU_CSSS_GMAIL_USERNAME'),
                        string(credentialsId: 'SFU_CSSS_GMAIL_PASSWORD', variable: 'SFU_CSSS_GMAIL_PASSWORD'),
                        string(credentialsId: 'CSSS_DISCORD_BOT_TOKEN', variable: 'CSSS_DISCORD_BOT_TOKEN'),
                        string(credentialsId: 'SFU_ENDPOINT_TOKEN', variable: 'SFU_ENDPOINT_TOKEN')
                    ]
                ) {
                    sh label: '', script: """bash -c \'
                        export BRANCH_NAME=${BRANCH_NAME};
                        export BASE_DIR=/home/csss;
                        export WEBSITE_SECRET_KEY="'"${WEBSITE_PROD_SECRET_KEY}"'";
                        export DEBUG=false;
                        export ENVIRONMENT=PRODUCTION;
                        export HOST_ADDRESS=sfucsss.org;

                        export GDRIVE_TOKEN_LOCATION="/home/csss/google_drive_api_token/token.pickle";
                        export GDRIVE_ROOT_FOLDER_ID="'"0B5w0O-VrxOd3UDg4Y3cyd3NFWEE"'";
                        export GITHUB_ACCESS_TOKEN="'"${GITHUB_ACCESS_TOKEN}"'";
                        export GITLAB_PRIVATE_TOKEN="'"${GITLAB_PRIVATE_TOKEN}"'";
                        export SFU_CSSS_GMAIL_USERNAME="'"${SFU_CSSS_GMAIL_USERNAME}"'";
                        export SFU_CSSS_GMAIL_PASSWORD="'"${SFU_CSSS_GMAIL_PASSWORD}"'";
                        export DISCORD_BOT_TOKEN="'"${CSSS_DISCORD_BOT_TOKEN}"'";
                        export GUILD_ID="'"228761314644852736"'";
                        export SFU_ENDPOINT_TOKEN="'"${SFU_ENDPOINT_TOKEN}"'";

                        export DB_PASSWORD="'"${WEBSITE_PROD_DB_PASSWORD}"'";
                        export STRIPE_PUBLISHABLE_KEY="'"${WEBSITE_PROD_STRIPE_PUBLISHABLE_KEY}"'";
                        export STRIPE_SECRET_KEY="'"${WEBSITE_PROD_STRIPE_SECRET_KEY}"'";
                        ./CI/validate_and_deploy/2_deploy/1_update_files_on_master_server.sh;
                        ssh csss@"\${HOST_ADDRESS}" "/home/csss/deploy_changes.sh";
                    \'"""
                }
            }
        }
    }
    post {
      always {
          script {
              if (fileExists('test_results/all-unit-tests.xml')){
                  junit skipPublishingChecks: true, testResults: 'test_results/all-unit-tests.xml'
              }
          }
      }
  }
}
