# Generated by Django 2.2.9 on 2020-02-01 03:10

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(location='/home/csss/media_root/'), upload_to='form_uploads/form_uploads/multiFileUploads/')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_uploads.UserSubmission')),
            ],
        ),
    ]
