# Generated by Django 2.2.13 on 2020-10-01 17:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='input_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(location='/media/jace/jace_usb_1/csss-site/media_root/'), upload_to='form_uploads/form_uploads/multiFileUploads/'),
        ),
    ]
