import json

from django.shortcuts import render

from elections.views.Constants_v2 import ELECTION_JSON_VALUE__DATE_AND_TIME_FORMAT, ELECTION_JSON_KEY__ELECTION_TYPE, \
    INPUT_REDIRECT_ELECTION__NAME, INPUT_REDIRECT_ELECTION_SUBMIT_AND_CONTINUE_EDITING__VALUE, \
    INPUT_REDIRECT_ELECTION_SUBMIT__VALUE, CREATE_NEW_JSON_ELECTION__NAME, \
    SAVE_AND_CONTINUE_EDITING_NEW_JSON_ELECTION__VALUE, SAVE_NEW_JSON_ELECTION__VALUE, ELECTION_JSON_KEY__DATE, \
    ELECTION_JSON_KEY__WEBSURVEY, ELECTION_JSON_KEY__NOMINEES, ELECTION_JSON_KEY__NOM_NAME, \
    ELECTION_JSON_KEY__NOM_POSITION_AND_SPEECH_PAIRINGS, ELECTION_JSON_KEY__NOM_POSITION_NAMES, \
    ELECTION_JSON_KEY__NOM_SPEECH, ELECTION_JSON_KEY__NOM_LINKEDIN, ELECTION_JSON_KEY__NOM_EMAIL, \
    ELECTION_JSON_KEY__NOM_FACEBOOK, \
    ELECTION_JSON_KEY__NOM_DISCORD, SAVE_NEW_JSON_ELECTION__BUTTON_ID, \
    SAVE_NEW_JSON_ELECTION_AND_CONTINUE_EDITING__BUTTON_ID, JS_FORMATTING_ERROR, ELECTION_JSON__KEY, \
    FORMAT_ELECTION_JSON__DIV_ID_NAME, USER_INPUTTED_ELECTION_JSON__KEY, USER_INPUTTED_ELECTION_JSON, \
    SAVE_NEW_JSON_ELECTION__BUTTON_ID_VALUE, SAVE_NEW_JSON_ELECTION_AND_CONTINUE_EDITING__BUTTON_ID_VALUE


def display_empty_election_json(request, context):
    """
    creates the dictionary that the user has to fill in to create an election

    Keyword Argument
    request -- the django request object
    context -- the context dictionary that needs to have the election dictionary template inserted into it

    Return
    takes user to the page where they are asked to fill in the JSON for the new election
    """
    context[ELECTION_JSON__KEY] = json.dumps(
        {
            ELECTION_JSON_KEY__ELECTION_TYPE: "",
            ELECTION_JSON_KEY__DATE: ELECTION_JSON_VALUE__DATE_AND_TIME_FORMAT,
            ELECTION_JSON_KEY__WEBSURVEY: "",
            ELECTION_JSON_KEY__NOMINEES: [
                {
                    ELECTION_JSON_KEY__NOM_NAME: "",
                    ELECTION_JSON_KEY__NOM_POSITION_AND_SPEECH_PAIRINGS: [
                        {ELECTION_JSON_KEY__NOM_POSITION_NAMES: [], ELECTION_JSON_KEY__NOM_SPEECH: "NONE"}],
                    ELECTION_JSON_KEY__NOM_FACEBOOK: "NONE", ELECTION_JSON_KEY__NOM_LINKEDIN: "NONE",
                    ELECTION_JSON_KEY__NOM_EMAIL: "NONE",
                    ELECTION_JSON_KEY__NOM_DISCORD: "NONE"
                }
            ]
        }
    )
    context.update({
        INPUT_REDIRECT_ELECTION__NAME: CREATE_NEW_JSON_ELECTION__NAME,
        INPUT_REDIRECT_ELECTION_SUBMIT_AND_CONTINUE_EDITING__VALUE: SAVE_AND_CONTINUE_EDITING_NEW_JSON_ELECTION__VALUE,
        INPUT_REDIRECT_ELECTION_SUBMIT__VALUE: SAVE_NEW_JSON_ELECTION__VALUE,
        SAVE_NEW_JSON_ELECTION__BUTTON_ID: SAVE_NEW_JSON_ELECTION__BUTTON_ID_VALUE,
        SAVE_NEW_JSON_ELECTION_AND_CONTINUE_EDITING__BUTTON_ID: SAVE_NEW_JSON_ELECTION_AND_CONTINUE_EDITING__BUTTON_ID_VALUE,
        FORMAT_ELECTION_JSON__DIV_ID_NAME: JS_FORMATTING_ERROR,
        USER_INPUTTED_ELECTION_JSON__KEY: USER_INPUTTED_ELECTION_JSON
    })
    return render(request, 'elections/create_election/create_election_json.html', context)
