# Generated by Django 2.2.9 on 2020-02-01 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NominationPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('election_type', models.CharField(choices=[('general_election', 'General Election'), ('by_election', 'By-Election')], default='General Election', max_length=16, verbose_name='Election Type')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date to be made Public')),
                ('websurvey', models.CharField(default='NONE', max_length=300, verbose_name='The link that the voters can use to vote on')),
            ],
            options={
                'verbose_name_plural': 'NominationPages',
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('exec_position', models.CharField(default='NA', max_length=40)),
                ('position', models.IntegerField(default=0)),
                ('speech', models.CharField(max_length=10000)),
                ('facebook', models.CharField(max_length=300, verbose_name='Facebook Link')),
                ('linked_in', models.CharField(max_length=300, verbose_name='LinkedIn Link')),
                ('email', models.CharField(max_length=300, verbose_name='Email Address')),
                ('discord', models.CharField(max_length=300, verbose_name='Discord Username')),
                ('nomination_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.NominationPage')),
            ],
        ),
    ]
