# Generated by Django 2.2.13 on 2020-07-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='exec_position',
            new_name='officer_position',
        ),
    ]
