# Generated by Django 2.2.13 on 2020-07-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20200706_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationpage',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
    ]
