# Generated by Django 2.2.13 on 2020-07-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20200708_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationpage',
            name='human_friendly_name',
            field=models.CharField(default='NONE', max_length=32),
        ),
    ]
