# Generated by Django 2.2.13 on 2020-12-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_nominationpage_human_friendly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='position',
            new_name='position_name',
        ),
    ]
