# Generated by Django 2.2.13 on 2021-02-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20201216_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NominationPage',
            new_name='Election',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='nomination_page',
            new_name='election',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='officer_position',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='position_name',
        ),
        migrations.CreateModel(
            name='NomineePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_position', models.CharField(default='NA', max_length=40)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Nominee')),
            ],
        ),
    ]
