# Generated by Django 2.2.13 on 2021-04-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20210406_2043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NominationPage',
            new_name='Election',
        ),
        migrations.AlterModelOptions(
            name='election',
            options={},
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='nomination_page',
            new_name='election',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='officer_position',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='position_name',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='speech',
        ),
        migrations.CreateModel(
            name='NomineeSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech', models.CharField(default='NA', max_length=30000)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Nominee')),
            ],
        ),
        migrations.CreateModel(
            name='NomineePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(default='NA', max_length=40)),
                ('position_index', models.IntegerField(default=0)),
                ('nominee_speech', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elections.NomineeSpeech')),
            ],
        ),
    ]
