# Generated by Django 2.2.13 on 2021-05-17 20:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20210406_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('human_friendly_name', models.CharField(default='NONE', max_length=32)),
                ('election_type', models.CharField(choices=[('general_election', 'General Election'), ('by_election', 'By-Election')], default='General Election', max_length=1000, verbose_name='Election Type')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date to be made Public')),
                ('websurvey', models.CharField(default='NONE', max_length=300, verbose_name='The link that the voters can use to vote on')),
            ],
        ),
        migrations.CreateModel(
            name='NomineePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(default='NA', max_length=40)),
                ('position_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NomineeSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech', models.CharField(default='NA', max_length=30000)),
            ],
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='linked_in',
            new_name='linkedin',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='nomination_page',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='officer_position',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='position_name',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='speech',
        ),
        migrations.DeleteModel(
            name='NominationPage',
        ),
        migrations.AddField(
            model_name='nomineespeech',
            name='nominee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Nominee'),
        ),
        migrations.AddField(
            model_name='nomineeposition',
            name='nominee_speech',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elections.NomineeSpeech'),
        ),
        migrations.AddField(
            model_name='nominee',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elections.Election'),
        ),
    ]
