# Generated by Django 2.2.13 on 2021-02-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20210202_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomineeposition',
            old_name='officer_position',
            new_name='position_name',
        ),
    ]
