# Generated by Django 2.2.13 on 2021-05-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20210406_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='nomination_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elections.NominationPage'),
        ),
    ]
