# Generated by Django 2.2.13 on 2021-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_auto_20210209_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineeposition',
            name='position_index',
            field=models.IntegerField(default=0),
        ),
    ]
