# Generated by Django 2.2.13 on 2021-04-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_auto_20210412_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='linked_in',
            new_name='linkedin',
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('general_election', 'General Election'), ('by_election', 'By-Election')], default='General Election', max_length=1000, verbose_name='Election Type'),
        ),
        migrations.AlterField(
            model_name='election',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
