# Generated by Django 2.2.13 on 2021-02-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_nomineeposition_position_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='nomineeposition',
            name='nominee',
        ),
        migrations.CreateModel(
            name='NomineeSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech', models.CharField(default='NA', max_length=10000)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Nominee')),
            ],
        ),
        migrations.AddField(
            model_name='nomineeposition',
            name='nominee_speech',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elections.NomineeSpeech'),
        ),
    ]
