# Generated by Django 2.2.13 on 2021-08-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_nomineelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('general_election', 'General Election'), ('by_election', 'By-Election'), ('council_rep_election', 'Council Rep Election')], default='General Election', max_length=1000, verbose_name='Election Type'),
        ),
    ]
