# Generated by Django 2.2.13 on 2021-06-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_nomineelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineelink',
            name='nominee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Nominee'),
        ),
    ]
