# Generated by Django 2.2.27 on 2022-08-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_auto_20210803_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='nomineelink',
            old_name='name',
            new_name='full_name',
        ),
    ]
