# Generated by Django 2.2.27 on 2023-03-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_nominee_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='discord_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nominee',
            name='discord_nickname',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nominee',
            name='discord_username',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nominee',
            name='sfuid',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='human_friendly_name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='websurvey',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='The link that the voters can use to vote on'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='discord',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='Discord Username'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='email',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='facebook',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='instagram',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='linkedin',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='LinkedIn Link'),
        ),
        migrations.AlterField(
            model_name='nomineespeech',
            name='speech',
            field=models.CharField(default=None, max_length=30000, null=True),
        ),
    ]
