# Generated by Django 2.2.27 on 2023-03-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_nomineelink_sfuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineelink',
            name='discord_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
