# Generated by Django 2.2.27 on 2023-05-03 01:55

import csss.PSTDateTimeField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_auto_20230411_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=csss.PSTDateTimeField.PSTDateTimeField(default=None, null=True),
        ),
    ]
