# Generated by Django 2.2.28 on 2023-11-29 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0018_election_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfuid', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
            ],
        ),
        migrations.CreateModel(
            name='VoterChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.NomineePosition')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Voter')),
            ],
        ),
    ]
