# Generated by Django 2.2.28 on 2024-02-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0018_election_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='human_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WebsurveyColumnPositionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websurvey_column', models.IntegerField()),
                ('position_name', models.CharField(default=None, max_length=1000, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
            ],
        ),
        migrations.CreateModel(
            name='VoterChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.NomineePosition')),
            ],
        ),
        migrations.CreateModel(
            name='PendingVoterChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nominee_name_mapped', models.BooleanField(default=False)),
                ('websurvey_column', models.IntegerField(default=None, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
            ],
        ),
    ]
