from elections.views.Constants import INPUT_REDIRECT_ELECTION__NAME, CREATE_NEW_ELECTION__NAME, \
    UPDATE_EXISTING_ELECTION__NAME, INPUT_REDIRECT_ELECTION_SUBMIT__VALUE, SAVE_ELECTION__VALUE, \
    INPUT_REDIRECT_ELECTION_SUBMIT_AND_CONTINUE_EDITING__VALUE, SAVE_AND_CONTINUE_EDITING_ELECTION__VALUE


def create_context_for_submission_buttons_html(context, create_new_election=False):
    context.update({
        INPUT_REDIRECT_ELECTION__NAME: CREATE_NEW_ELECTION__NAME if create_new_election
        else UPDATE_EXISTING_ELECTION__NAME,
        INPUT_REDIRECT_ELECTION_SUBMIT__VALUE: SAVE_ELECTION__VALUE,
        INPUT_REDIRECT_ELECTION_SUBMIT_AND_CONTINUE_EDITING__VALUE: SAVE_AND_CONTINUE_EDITING_ELECTION__VALUE
    })
