# Generated by Django 2.2.27 on 2022-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=5000)),
                ('file_name', models.CharField(max_length=5000)),
                ('class_name', models.CharField(max_length=5000)),
                ('schedule', models.CharField(max_length=500)),
            ],
        ),
    ]
