# Generated by Django 2.2.27 on 2022-09-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='file_name',
        ),
    ]
