# Generated by Django 2.2.27 on 2022-12-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csss', '0002_auto_20220906_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='job_name',
            field=models.CharField(max_length=5000, unique=True),
        ),
    ]
