# Generated by Django 2.2.27 on 2023-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csss', '0003_auto_20230109_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssserror',
            name='endpoint',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cssserror',
            name='request',
            field=models.CharField(default=None, max_length=100000, null=True),
        ),
    ]
