# Generated by Django 2.2.27 on 2023-01-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csss', '0004_auto_20230110_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssserror',
            name='type',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
