# Generated by Django 2.2.28 on 2023-07-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csss', '0006_auto_20230411_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssserror',
            name='file_path',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
