node {
   stage('Validate Code') {
    // Trigger: GitHub webhook whenever a branch is deleted
    // Action: Delete branch's testing channels and containers

    def object = readJSON text: "${payload}"
    def BRANCH_NAME = object.ref
    sh label: '', script: """bash -c \'
        git checkout ${BRANCH_NAME}
        export COMPOSE_PROJECT_NAME=TEST_WEBSITE_{BRANCH_NAME};
        export CONTAINER_HOME_DIR=/usr/src/app;
        export CONTAINER_TEST_DIR=\${CONTAINER_HOME_DIR}/tests;
        export TEST_RESULT_FILE_NAME=all-unit-tests.xml;
        export LOCALHOST_TEST_DIR=test_results;
        export LOCALHOST_TEST_DIR=${WORKSPACE}/\${LOCALHOST_TEST_DIR};

        export DOCKER_TEST_CONTAINER=\${COMPOSE_PROJECT_NAME}_pytest;
        export DOCKER_TEST_IMAGE=\${COMPOSE_PROJECT_NAME}_csss_site_pytest;

        ./CI/validate-formatting.sh;
    \'"""
   }
}
