pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage('Validate Formatting') {
            steps {
                sh label: '', script: """bash -c \'
                    ./csss-site/test/lineEndings.sh
                    export ENVIRONMENT=TEST;
                    export COMPOSE_PROJECT_NAME=TEST_WEBSITE_${BRANCH_NAME};

                    export CONTAINER_HOME_DIR=/usr/src/app;
                    export CONTAINER_TEST_DIR=\${CONTAINER_HOME_DIR}/tests;
                    export CONTAINER_SRC_DIR=\${CONTAINER_HOME_DIR}/src;

                    export LOCALHOST_SRC_DIR=${WORKSPACE}/website/src/;
                    export LOCALHOST_TEST_DIR=test_results;
                    export TEST_RESULT_FILE_NAME=all-unit-tests.xml;
                    export LOCALHOST_TEST_DIR=${WORKSPACE}/\${LOCALHOST_TEST_DIR};

                    export DOCKER_TEST_IMAGE=\${COMPOSE_PROJECT_NAME}_website_pytest;
                    export DOCKER_TEST_CONTAINER=\${COMPOSE_PROJECT_NAME}_pytest;
                    ./CI/validate-formatting.sh;
                \'"""
            }
        }
        stage('Deploy to Server') {
            when {
                branch 'master'
            }
            steps {
                sh label: '', script: """bash -c \'
                    # remove all old and replace with newer code. will make sure that the migrations are not deleted as they need to be
                    # persistent through the changes
                    ssh csss@sfucsss.org "find /home/csss/csss-site/csss-site/src -mindepth 1 ! -regex '/migrations\(/.*\)?' -delete"
                    ssh csss@sfucsss.org "mkdir -p /home/csss/csss-site/csss-site/src"
                    scp -r "csss-site/src"/* csss@sfucsss.org:/home/csss/csss-site/csss-site/src/

                    # transfer requirements file and script that is used to setup the website
                    scp -r "requirements.txt" csss@sfucsss.org:/home/csss/csss-site/requirements.txt
                    scp -r "CI/deploy_changes.sh" csss@sfucsss.org:/home/csss/deploy_changes.sh

                    ssh csss@sfucsss.org "/home/csss/deploy_changes.sh"
                \'"""
            }
        }
    }
    post {
      always {
          script {
              if (fileExists('test_results/all-unit-tests.xml')){
                  junit 'test_results/all-unit-tests.xml'
              }
          }
      }
  }
}
