# Generated by Django 2.2.9 on 2020-02-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerUpdatePassphrase',
            fields=[
                ('passphrase', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
