# Generated by Django 2.2.13 on 2020-07-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficerUpdatePassphrase',
        ),
    ]
